### ISSUE TITLE
ramachandran plot out of the borders 

### ISSUE THREAD

**Issue by lpravda** [ondraab/rama#5]
In Safari browser (1tqn and general case ramachandran diagram) the entire diagram stretched far from actual borders

![screen shot 2018-02-13 at 10 45 45](https://user-images.githubusercontent.com/16133456/36146028-216f44b2-10ab-11e8-8e5e-9624aff9c4b6.png)

**Comment by ondraab** [comment]
Should be working now, added border to contours.
